SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRANSACTION
SELECT * FROM Album WHERE AlbumId = 17
WAITFOR DELAY '00:00:10'
SELECT * FROM Album WHERE AlbumId = 17

UPDATE Album SET ReleaseDate = '1973-01-01' WHERE AlbumId = 17
COMMIT TRANSACTION