SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRANSACTION
SELECT * FROM Album;
WAITFOR DELAY '00:00:10'
SELECT * FROM Album;
COMMIT TRANSACTION


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
SELECT * FROM Album;
WAITFOR DELAY '00:00:10'
SELECT * FROM Album;
COMMIT TRANSACTION
