/**
SELECT * FROM Users;
INSERT INTO Users (UId, Name, City, DateOfBirth) VALUES (1, 'Ion Popescu', 'Bucuresti', '05-30-2000');

SELECT * FROM Posts;
**/

-- non-repeatable read issue
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION 

SELECT * FROM Posts P WHERE P.PId = 1;
WAITFOR DELAY '00:00:10';
SELECT * FROM Posts P WHERE P.PId = 1;

COMMIT TRANSACTION



SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION 

SELECT * FROM Posts P WHERE P.PId = 1;
WAITFOR DELAY '00:00:10';
SELECT * FROM Posts P WHERE P.PId = 1;

COMMIT TRANSACTION
